name: git_project
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.5 <4.0.0'

dependencies:
  flutter_sizer: ^1.0.4
  validators: ^3.0.0
  smooth_page_indicator: ^1.1.0
  expandable_text: 2.3.0
  get: ^4.6.6
  flutter_spinkit: ^5.2.0
  flutter_native_splash: ^2.3.9
  flutter:
    sdk: flutter


dev_dependencies:
  build_runner:
  flutter_gen_runner:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/logo.jpg
    - assets/images/conf.jpg
    - assets/images/hashtag.png
    - assets/icons/user.gif
    - assets/icons/home.png
    - assets/icons/pencil.png
    - assets/icons/profile.png
    - assets/icons/edite_profile.png
    - assets/icons/welcome.png
    - assets/images/youtube.png
    - assets/images/category/hearingLoss_1.png
    - assets/images/category/hearingLoss_2.png
    - assets/images/category/hearingLoss_3.png
    - assets/images/category/hearingLoss_4.png
    - assets/images/category/hearingLoss_5.png
    - assets/images/category/hearingLoss_6.png

  fonts:
    - family: Dubia
      fonts:
        - asset: assets/fonts/Dubai-Light.ttf
          weight: 100
        - asset: assets/fonts/Dubai-Regular.ttf
          weight: 300
        - asset: assets/fonts/Dubai-Medium.ttf
          weight: 500
        - asset: assets/fonts/Dubai-Bold.ttf
          weight: 700
